### ISSUE TITLE
crash on trying to detect config folder

### ISSUE THREAD

**Issue by undertherain** [mbdevpl/ingit#3]
```
blackbird@ashtree:~/Projects$ ingit
Traceback (most recent call last):
  File "/home/blackbird/.local/bin/ingit", line 7, in <module>
    from ingit.__main__ import main
  File "/home/blackbird/.local/lib/python3.6/site-packages/ingit/__main__.py", line 3, in <module>
    from .main import main
  File "/home/blackbird/.local/lib/python3.6/site-packages/ingit/main.py", line 8, in <module>
    from ._version import VERSION
  File "/home/blackbird/.local/lib/python3.6/site-packages/ingit/_version.py", line 5, in <module>
    VERSION = predict_version_str()
  File "/home/blackbird/.local/lib/python3.6/site-packages/version_query/query.py", line 62, in predict_version_str
    return predict_caller(2).to_str()
  File "/home/blackbird/.local/lib/python3.6/site-packages/version_query/query.py", line 58, in predict_caller
    return query_folder(here, True)
  File "/home/blackbird/.local/lib/python3.6/site-packages/version_query/query.py", line 39, in query_folder
    return query_package_folder(path, search_parent_directories=search_parent_directories)
  File "/home/blackbird/.local/lib/python3.6/site-packages/version_query/py_query.py", line 41, in query_package_folder
    raise ValueError(paths, metadata_json_paths, pkg_info_paths)
ValueError: ([PosixPath('/home/blackbird/.local/lib/python3.6/site-packages/ingit'), PosixPath('/home/blackbird/.local/lib/python3.6/site-packages'), PosixPath('/home/blackbird/.local/lib/python3.6'), PosixPath('/home/blackbird/.local/lib'), PosixPath('/home/blackbird/.local'), PosixPath('/home/blackbird'), PosixPath('/home'), PosixPath('/')], [], [])
```

**Comment by undertherain** [comment]
ingit version: 0.3.0
Ubuntu 17.10 \n \l
Python 3.6.3
:)

**Comment by mbdevpl** [comment]
Oh, it's an issue with `version_query`. What is output of `python3.6 -m version_query --version`?

**Comment by undertherain** [comment]
```
blackbird@ashtree:~$ python3.6 -m version_query --version
usage: version_query [-h] [-i] [-p] path
version_query: error: the following arguments are required: path
```

**Comment by undertherain** [comment]
but
```
blackbird@ashtree:~$ pip3 show version_query
Name: version-query
Version: 0.4.0
``` :)

**Comment by undertherain** [comment]
upgrading system_query did not fix the problem, but ingit is working on m other PC with very similar version of everything

**Comment by undertherain** [comment]
solved somehow by uninstalling package twice(!) and installing again to clean old package info in site-packages

**Comment by mbdevpl** [comment]
Sadly, pip sometimes does this...

https://github.com/pypa/pip/issues/3089 

That issue is closed because it's hard to reproduce, but still, it definitely happens sometimes to some unlucky ones. During package update, the old version's package metadata is not removed.
